### ISSUE TITLE
task-cancel failed when task is running

### ISSUE THREAD

**Issue by kidleaf-jiang** [hugegraph/hugegraph-tools#50]
task-cancel cmd：
![image](https://user-images.githubusercontent.com/7587298/72050315-cb776100-32fb-11ea-8438-be64b4164495.png)

task is been running for two hours
![image](https://user-images.githubusercontent.com/7587298/72050245-a387fd80-32fb-11ea-89d7-9c20cf10394f.png)

only one task is running 
![image](https://user-images.githubusercontent.com/7587298/72050289-bb5f8180-32fb-11ea-9b35-a258238cbf3a.png)

**Comment by javeme** [comment]
This bug is caused by failure task status has not been saved to backend store(the root cause is result size exceeded 64k, and failed to save), so its status is still RUNNING even the task is finished, if call cancel() then the task will be loaded from backend store and its scheduler is null. 
fixed at:
https://github.com/hugegraph/hugegraph/compare/task-bug?expand=1#diff-4279711806c15ce08a30cd3506573331R212
https://github.com/hugegraph/hugegraph/compare/task-bug?expand=1#diff-3401d80efb37b0d0d9b1fd63de15e450R82
